### PR TITLE
ci: Replace reviewdog with plain Rubocop

### PR DESCRIPTION
**Pull request by nschonni**
Swap reviewdog with a plain Rubocop call, along with a problemmatcher to show issues on the PR files tab

### CODE REVIEW

**Comment by nschonni** [comment]
Had to add the second commit to quote the ruby version numbers, as I remembered with the first failure https://github.com/nschonni/rspec-github/actions/runs/4388566499/jobs/7685202341 that GitHub/Yaml does a weird thing with the trailing 0 in the numbers like `3.0`. They get parsed down to `3`, which gets interpreted as `3.2` as the latest `3.x` release.
Now passing with minimal changes https://github.com/nschonni/rspec-github/actions/runs/4390033688/jobs/7688162990

**Comment by StefSchenkelaars** [comment]
@LuukvH Can you maybe update the merge settings?
- Remove reviewdog requirement
- Replace "RSpec tests ruby 3" with "RSpec tests ruby 3.0"

**Comment by nschonni** [comment]
@LuukvH are you interested in this one, or should I close it?

**Comment by LuukvH** [comment]
@nschonni I don't know this action, and I'am not sure what it does. Just wanted to checkout that repo first (support / code etc) before deciding to merge it.

**Pull request closed without merging**
